# Generated by Django 3.2.5 on 2022-01-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
