# Generated by Django 3.2.5 on 2022-01-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collegemodel_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
