# Generated by Django 3.2.5 on 2022-01-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collegemodel_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
            ],
        ),
    ]
