# Generated by Django 3.2.5 on 2022-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pdfmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='hostel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='nirf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
